---
- name: Create DNS Zone
  route53_zone:
    aws_access_key: "{{ AWS_ACCESS_KEY_ID | default(omit) }}"
    aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY | default(omit) }}"
    zone: "{{ cloud_dns_zone }}"
    state: present
  tags:
    - cloud_dns

- name: Add instance DNS record
  route53:
    aws_access_key: "{{ AWS_ACCESS_KEY_ID | default(omit) }}"
    aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY | default(omit) }}"
    command: "{{ cloud_dns_record_command | default('create') }}"
    overwrite: yes
    zone: "{{ cloud_dns_zone }}"
    record: "{{ cloud_dns_record }}"
    type: "{{ cloud_dns_record_type | default('A') }}"
    value: "{{ cloud_dns_record_value }}"
    ttl: "{{ cloud_dns_record_type | default('60') }}"
    wait: yes
  tags:
    - cloud_dns